spring:
 profiles:
   active: local

---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: custtrans    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/custtrns
    username: developer
    password: ********
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web: 
     exposure:
       include: "*"
       exclude: "env,beans"

logging:
  level:
    ROOT: WARN

welcome:
  message: custtrns Service started

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: custtrans    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/custtrns
    username: developer
    password: ********
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web: 
     exposure:
       include: "*"
       exclude: "env,beans"

logging:
  level:
    ROOT: WARN

welcome:
  message: custtrns Service started

